version: '3.9'

services:
  user-registration-service:
    depends_on:
      - storage
    restart: unless-stopped
    build:
      context: .
    ports:
      - 80:80
    environment:
      - Host=0.0.0.0
      - Port=80
      - DatabaseUrl=postgres://postgres:postgres@storage:5432/postgres
      - JwtSecret=4781abbb-5d19-4e18-9f90-08c64b8d135f
      - AccessTokenTtl=0h2m0s
      - RefreshTokenTtl=24h0m0s
      - EmailAddres=usr.rgstr.srv.example@gmail.com
      - EmailPassword=
      - EmailHost=smtp.gmail.com
      - EmailCodeTtl=0h5m0s
  storage:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
